# User config
author: "Katie Hughes"
tagline: "Katie Hughes's Portfolio"
description: "Masters in Robotics student at Northwestern University"
keywords: "Keywords"
email: "khughes1@u.northwestern.edu"
resume: "https://drive.google.com/file/d/1RJ5KKuj0wv6LfEW1M3z21ewzJm6gg70u/view?usp=sharing"
linkedin: "https://www.linkedin.com/in/katie-rees-hughes/"
github: "https://github.com/katie-hughes"


# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed