# Site settings
title:              Katie Hughes
email:              katiereeshughes@gmail.com
description:        "My Portfolio"
url:                "http://localhost:4000"
baseurl:            https://katie-hughes.github.io/

# File structure settings
image_path:         /public/images

# Build settings
markdown:           kramdown
permalink:          pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
