# User config
author: "Katie Hughes"
tagline: "Katie Hughes's Portfolio"
description: "My description"
keywords: "Keywords"
email: "khughes1@u.northwestern.edu"
resume: "resumelink"
linkedin: "https://www.linkedin.com/in/katie-rees-hughes/"
github: "https://github.com/katie-hughes"


# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed